### ISSUE TITLE
IntranetUserJS: Changes to search page

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-changes-to-search-page#1]
Plugin IntranetUserJS: Changes to search page

Testaus:

Poista rimpsut

//Indeksointi-työryhmän päättämät muutokset /
// Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
(saattaa olla eri otsikolla nimettynä, kyse yhdestä rimpsusta)
intranetUserJS-asetuksesta.

ja

/* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */

Aktivoi plugin.

Tarkista, että tarkassa haussa hakutermit, otsikot ja alasvetovalikot sisältävät edelleen halutut muutokset.

**Comment by lmstrand** [comment]
Seuranta kimpoista. Kommentoi tikettiä, kun muutos tehty ja testattu omassa kimpassa.

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski
- [x] TäTi

**Comment by lmstrand** [comment]
Tähän samaan pluginiin on nyt lisätty Vaskista napattu /* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */ -rimpsukin. Tämä Vaskin versio osaa katsoa, että ollaanko hakua muokkaamassa, eikä ylikirjoita noita termejä silloin, joten vanhan haun hakutermit säilyvät. Tämäkin rimpsu on siis poistettava intranetUserJS-asetuksesta, ettei ole päällekkäin pluginversion kanssa.

**Comment by pknuuti** [comment]
Poistin Vaaran nextiltä mainitut rimpsut IntrranetUserJS-asetuksesta ja laitoin päälle tuon pluginin. Kun käynnistin pluginin, näkyi otsikot oikein (ensin en hoksannut käynnistää sitä, vain aktivoin).

**Comment by ReettaSiili** [comment]
Näyttäisi toimivan Siilin nextillä, otsikot ja mainitut termit oikein.

**Comment by MikkoLiimatainen** [comment]
Plugarissa näyttäisi olevan mukana myös location-arvon muuttaminen loc-arvoksi. Tämä muuttui jossain edellisessä versiossa niin, että hyllypaikkahakuun käytetään location,wrdl-arvoa. Tämä rimpsu poistettiin silloin käytöstä, kun haku toimii ilmankin ja haun muokkaukseen tulee sama haussa käytetty location,wrdl-arvo automaattisesti.

**Comment by lmstrand** [comment]
> Plugarissa näyttäisi olevan mukana myös location-arvon muuttaminen loc-arvoksi. Tämä muuttui jossain edellisessä versiossa niin, että hyllypaikkahakuun käytetään location,wrdl-arvoa. Tämä rimpsu poistettiin silloin käytöstä, kun haku toimii ilmankin ja haun muokkaukseen tulee sama haussa käytetty location,wrdl-arvo automaattisesti.

Tarpeeton loc-muutos poistettu ja muutos viety nexteille.

**Comment by LeenaKinnunen** [comment]
Lappissa otettu käyttöön ja toimii, paitsi: ei nextillä eikä tuotannossa Lisärajoitukset -valikkoa näkyvissä, joka on IntranetuserJS:ssä nämä rivit: 
   $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */

**Comment by piiaseme** [comment]
OUTIssa muutos tehty ja testattu. Toimii kuten pitää.

**Comment by ElinaUotila** [comment]
Kirkesissä muutos tehty ja testattu.

**Comment by AnneliO** [comment]
> Lappissa otettu käyttöön ja toimii, paitsi: ei nextillä eikä tuotannossa Lisärajoitukset -valikkoa näkyvissä, joka on IntranetuserJS:ssä nämä rivit: $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */ $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */

En tiedä, oliko tämä vain huomio vai ongelma, mutta Lapissa on IntranetUserCSS:ssä piilotettu nuo Lisärajaukset tällä rimpsulla:

```
/* Tarkan haun Lisärajuslaatikon piilotus */ /* Toimii 17.2.2023 MLI */ /* Jos tämän laittaa päälle, menettää valikoihin lisätyt hakuehdot */
#catalog_advsearch #subtype { display:none; } 
```

**Comment by LastuJanneS** [comment]
Tämäkin kunnossa Lastussa

**Comment by AnneliO** [comment]
Tämä on nyt kunnossa kaikissa kimpoissa, joten suljen tiketin.
